### ISSUE TITLE
Generate StructuralElementInstanceValidatorTest with a new concept

### ISSUE THREAD

**Issue by andriikovalov-dlr** [virtualsatellite/VirtualSatellite4-Core#165] opened 2019-07-23 07:49 UTC
To increase code coverage.

**Comment by SaMuellerDLR** [comment] 2019-11-29 08:46
Duplicate of https://github.com/virtualsatellite/VirtualSatellite4-Core/issues/305

**Closed by SaMuellerDLR** 2019-11-29 08:46 UTC
Labels: comfort/usability, duplicate
