### ISSUE TITLE
NPE on EcoreUtil.resolve sometimes on update

### ISSUE THREAD

**Issue by andriikovalov-dlr** [virtualsatellite/VirtualSatellite4-Core#389] opened 2019-12-06 10:15 UTC
We don't know how to reproduce it reliably, but we saw it several times at CEF.
Error appears on updating, but apparently it's EcoreUtil.resolve breaking. May have something to do with deletion of elements before updating.
After restarting VirSat error disappears.
```
!ENTRY org.eclipse.core.resources 4 2 2019-12-04 11:29:47.383
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:190)
	at de.dlr.sc.virsat.project.resources.VirSatResourceSet.updateDiagnostic(VirSatResourceSet.java:1087)
	at de.dlr.sc.virsat.project.editingDomain.VirSatTransactionalEditingDomain.saveAll(VirSatTransactionalEditingDomain.java:264)
	at de.dlr.sc.virsat.model.calculation.compute.IncrementalEquationBuilder$2.execute(IncrementalEquationBuilder.java:187)
	at org.eclipse.emf.workspace.EMFCommandOperation.doExecute(EMFCommandOperation.java:119)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
	at de.dlr.sc.virsat.project.editingDomain.VirSatWorkspaceCommandStack.executeNoUndo(VirSatWorkspaceCommandStack.java:61)
	at de.dlr.sc.virsat.model.calculation.compute.IncrementalEquationBuilder.transactionaIncrementalBuild(IncrementalEquationBuilder.java:211)
	at de.dlr.sc.virsat.model.calculation.compute.IncrementalEquationBuilder.build(IncrementalEquationBuilder.java:110)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by PhilMFischer** [comment] 2019-12-10 06:54
Cannot identify issue for the moment. Try to improve logging for the short run. See #394.

**Comment by PhilMFischer** [comment] 2019-12-10 06:54
Cannot identify issue for the moment. Try to improve logging for the short run. See #394.

**Comment by SaMuellerDLR** [comment] 2020-02-26 09:56
Added logging but cannot reproduce. Closing.

**Closed by SaMuellerDLR** 2020-02-26 09:56 UTC
Labels: bug, wontfix
